import '../styles/globals.css'
import { Provider } from "react-redux";
import Head from "next/head";
import store from "../reducer/store";
import { Nav, NavItem, NavLink } from "reactstrap";
import "bootstrap/dist/css/bootstrap.min.css";
function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <div>
          <Nav>
            <NavItem>
              <NavLink active href="/">
                handle image
              </NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="gallery">gallery</NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="/login">Login</NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="/signin">sign in</NavLink>
            </NavItem>
            <NavItem>
              <NavLink href="/images_anothers">images_anothers</NavLink>
            </NavItem>
           
          </Nav>
        </div>
        <Component {...pageProps} />
      </Provider>
    </>
  );

  
}

export default MyApp
